"""Episode service for TVBF"""
import azure.functions as func

from tvbingefriend_episode_service.blueprints import bp_get_show_episodes
from tvbingefriend_episode_service.blueprints import bp_health_monitoring
from tvbingefriend_episode_service.blueprints import bp_start_get_all
from tvbingefriend_episode_service.blueprints import bp_updates_manual
from tvbingefriend_episode_service.blueprints import bp_updates_timer
from tvbingefriend_episode_service.blueprints import bp_get_episodes_by_season

app = func.FunctionApp()

app.register_blueprint(bp_get_show_episodes)
app.register_blueprint(bp_health_monitoring)
app.register_blueprint(bp_start_get_all)
app.register_blueprint(bp_updates_manual)
app.register_blueprint(bp_updates_timer)
app.register_blueprint(bp_get_episodes_by_season)