"""Create episodes table

Revision ID: 001
Revises: 
Create Date: 2024-08-31 13:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('airdate', sa.Date(), nullable=True),
    sa.Column('airtime', sa.String(length=255), nullable=True),
    sa.Column('airstamp', sa.String(length=255), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('rating', mysql.JSON(), nullable=True),
    sa.Column('image', mysql.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('_links', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    # ### end Alembic commands ###