"""add db indexes

Revision ID: b6d87d5df92f
Revises: 001
Create Date: 2025-09-21 16:43:58.994681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6d87d5df92f'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episodes', 'url',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.create_index('idx_episodes_show_id', 'episodes', ['show_id'], unique=False)
    op.create_index('idx_episodes_show_season_number', 'episodes', ['show_id', 'season', 'number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_episodes_show_season_number', table_name='episodes')
    op.drop_index('idx_episodes_show_id', table_name='episodes')
    op.alter_column('episodes', 'url',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    # ### end Alembic commands ###
